Repository made-thoughts/mayflower, pull requests merged in 2023-01, with the labels that each got.

#6 Add some basic stuff
  .gitignore
  build.gradle.kts
  gradle.properties
  mayflower/build.gradle.kts
  mayflower/src/main/java/io/github/madethoughts/mayflower/MayflowerPlugin.java
  mayflower/src/main/java/io/github/madethoughts/mayflower/PaperPlugin.java
  mayflower/src/main/java/io/github/madethoughts/mayflower/lifecycle/event/DisableEvent.java
  mayflower/src/main/java/io/github/madethoughts/mayflower/lifecycle/event/EnableEvent.java
  mayflower/src/main/java/io/github/madethoughts/mayflower/lifecycle/event/LoadEvent.java
  settings.gradle.kts
  test_plugin/build.gradle.kts
  test_plugin/src/main/java/io/github/madethoughts/mayflower/testplugin/TestPlugin.java
  test_plugin/src/main/resources/plugin.yml
Labels: enhancement

#9 Style/general codestyle
  .github/workflows/conventional_commits.yml
  .github/workflows/gradle.yml
  .github/workflows/version_branch_create.yml
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  README.md
  buildSrc/gradle/wrapper/gradle-wrapper.properties
  mayflower/src/main/java/io/github/madethoughts/mayflower/MayflowerPlugin.java
  mayflower/src/main/java/io/github/madethoughts/mayflower/PaperPlugin.java
  mayflower/src/main/java/io/github/madethoughts/mayflower/lifecycle/event/package-info.java
  mayflower/src/main/java/io/github/madethoughts/mayflower/package-info.java
  test_plugin/src/main/java/io/github/madethoughts/mayflower/testplugin/package-info.java
Labels: chore

#12 Include "micronaut-context" instead of "micronaut-runtime"
  mayflower/build.gradle.kts
Labels: dependencies

#15 Update gradle wrapper binary
  gradle/wrapper/gradle-wrapper.jar
Labels: chore

#16 test: Verify plugin load in ci
  .github/workflows/gradle.yml
  test_plugin/src/main/java/io/github/madethoughts/mayflower/testplugin/ShutdownRunner.java
Labels: ci
